openapi: 3.0.0
info:
  title: Rootstock Blockscout API Integration
  description: API contract for interacting with Rootstock Blockscout explorer for contract verification and ABI fetching
  version: 1.0.0

servers:
  - url: https://explorer.rsk.co/api
    description: Rootstock Mainnet Blockscout
  - url: https://explorer.testnet.rsk.co/api
    description: Rootstock Testnet Blockscout

paths:
  /v2/smart-contracts/{address}:
    get:
      summary: Get contract verification status and ABI
      description: Fetches contract source code, ABI, and verification details from Blockscout
      operationId: getSmartContract
      parameters:
        - name: address
          in: path
          required: true
          description: Contract address (0x-prefixed hex)
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{40}$'
      responses:
        '200':
          description: Contract details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmartContractResponse'
        '404':
          description: Contract not found or not verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded (max 10 requests/second)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v2/addresses/{address}:
    get:
      summary: Get address details
      description: Fetches address information including whether it's a contract, proxy status, and basic metadata
      operationId: getAddress
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{40}$'
      responses:
        '200':
          description: Address details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressResponse'

  /v2/smart-contracts/{address}/methods-read:
    get:
      summary: Get contract read methods
      description: Fetches available read methods from verified contract ABI
      operationId: getReadMethods
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Read methods retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractMethod'

components:
  schemas:
    SmartContractResponse:
      type: object
      properties:
        is_verified:
          type: boolean
          description: Whether the contract is verified on Blockscout
        name:
          type: string
          description: Contract name from verification
          nullable: true
        abi:
          type: array
          description: Contract ABI JSON array
          items:
            type: object
        compiler_version:
          type: string
          nullable: true
        optimization_enabled:
          type: boolean
          nullable: true
        constructor_args:
          type: string
          nullable: true
        evm_version:
          type: string
          nullable: true
        source_code:
          type: string
          nullable: true
        file_path:
          type: string
          nullable: true
        additional_sources:
          type: array
          items:
            type: object
        proxy_type:
          type: string
          enum: [eip1967, eip1822, eip1167, unknown, null]
          nullable: true
          description: Proxy pattern if detected
        implementation_address:
          type: string
          pattern: '^0x[a-fA-F0-9]{40}$'
          nullable: true
          description: Implementation contract address for proxies

    AddressResponse:
      type: object
      properties:
        hash:
          type: string
          description: Address hash
        is_contract:
          type: boolean
          description: Whether this address is a contract
        implementation_address:
          type: string
          nullable: true
          description: For proxy contracts, the implementation address
        proxy_type:
          type: string
          nullable: true
        token:
          type: object
          nullable: true

    ContractMethod:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [function, constructor, fallback, receive]
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/ABIParameter'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/ABIParameter'
        stateMutability:
          type: string
          enum: [pure, view, nonpayable, payable]

    ABIParameter:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          description: Solidity type (address, uint256, bytes, etc.)
        internalType:
          type: string
          nullable: true
        components:
          type: array
          nullable: true
          description: For tuple types
          items:
            $ref: '#/components/schemas/ABIParameter'

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message

  securitySchemes: {}

# Integration Notes
x-integration-notes:
  rate-limiting:
    description: Blockscout imposes a 10 requests/second limit per IP
    strategy: Implement client-side rate limiting with queue and exponential backoff

  caching:
    description: ABI responses should be cached to minimize API calls
    strategy: localStorage with 24-hour TTL, sessionStorage for current session
    invalidation: Manual cache clear in settings UI

  error-handling:
    404-not-verified:
      action: Show "Contract not verified" modal, prompt for manual ABI input
    429-rate-limit:
      action: Queue request with exponential backoff (1s, 2s, 4s, 8s max)
    network-error:
      action: Retry up to 3 times, then fallback to manual ABI input

  proxy-detection:
    eip1967:
      slot: "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc"
      description: Transparent proxy pattern
    eip1822:
      slot: "0xc5f16f0fcc639fa48a6947836d9850f504798523bf8c9a3a87d5876cf622bcf7"
      description: Universal upgradeable proxy
    fallback:
      description: If Blockscout doesn't detect proxy, read storage slots directly using viem
